version: "3.8"
services:
  cakelandish:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    command: ["deno", "run", "--allow-net", "--allow-read", "--allow-write", "--allow-env", "--unstable-kv", "main.ts"]
